[package]
name = "antelope_transactions"
edition = "2021"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# substreams-entity-change = "1.3"
substreams-entity-change = { git = "https://github.com/streamingfast/substreams-sink-entity-changes", branch = "develop", package = "substreams-entity-change" }
substreams-antelope = "0.4"
substreams = "0.5"
serde_json = "1.0"
itertools = "^0.13"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"

